### ISSUE TITLE
Write C docs

### ISSUE THREAD

**Issue by dimonomid** [mongoose-os-libs/arduino-adafruit-tsl2561#1]
This lib has nice JS docs, but sadly not so nice C docs. Docs get rendered here: https://mongoose-os.com/docs/reference/api.html#arduino-adafruit-tsl2561

Could you please write C docs in `include/mgos_arduino_adafruit_tsl2561.h`, and also move `include/TSL2561.h` to `src` since it's not supposed to be used by the clients?

**Comment by pedalPusher68** [comment]
ok.  How do I get the latest version to be pulled down with a mos 1.23 build?

**Comment by dimonomid** [comment]
versioned mos by default uses lib versions tagged with the version number, so mos 1.23 will use tag 1.23 of this lib: https://github.com/mongoose-os-libs/arduino-adafruit-tsl2561/releases/tag/1.23

**Comment by pedalPusher68** [comment]
done and committed
